### ISSUE TITLE
pub.dev

### ISSUE THREAD

**Issue by dnys1** [TylerSustare/aws_sdk#1]
Hey @TylerSustare!

I'm a member of the AWS Amplify Flutter team. We are preparing to release an AWS SDK for Dart in the near future and I noticed you currently had the `aws_sdk` name in use on pub.dev. I wanted to see if you had plans for it and/or if you'd be open to parting with it and transferring it to our team?

All the best!
Dillon

**Comment by TylerSustare** [comment]
Hi @dnys1 👋 

That's great to hear! I initially started this trying to bring an AWS SDK to Flutter & Dart, so hearing that AWS is interested in working on the same is great! I do have `aws_sdk` on pub.dev and have been initially interested to use it for my project. However, I would love to work with AWS on an agreement. Would you be able to have a representative email me at tyler@sustare.com to discuss it?

Thank you for reaching out!

**Comment by dnys1** [comment]
Sounds great, thanks @TylerSustare!

**Comment by kemitix** [comment]
Was there any progress with this? Or could AWS not use `aws_sdk_dart`, following a common pattern for their SDKs, e.g. `aws-sdk-js` and `aws-sdk-java`? It's a blocker for anyone wanting to do any development that integrates with AWS.

**Comment by TylerSustare** [comment]
@dnys1 No worries, but it's been 6 months and no one from AWS has contacted me. Should I close this?

**Comment by dnys1** [comment]
Hi @TylerSustare, apologies for the lack of response. I will close this for now, as there have been some unforeseen setbacks internally. I hope we can deliver an AWS SDK for Dart in the near future!
